#!/bin/sh

# $Id: macvpn,v 1.1 2012-12-12 06:07:23 quixote Exp $
#Copyright 2012 Don Eisele
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

if [ "$1" == "-h" ]; then
  echo "Usage: $0 start   - start VPN daemons"
  echo "       $0 stop    - stop VPN daemons - kill processes left open"
  echo "       $0         - status: list processes, and count of network ports in CLOSE_WAIT"
  exit
fi

if [ "`id -u`" == "0" ]; then 
   SUDO=""
else 
   SUDO="sudo"
fi

if [ "$1" == "start" ]; then
  $SUDO launchctl load -w /Library/LaunchDaemons/com.cisco.anyconnect.vpnagentd.plist
elif [ "$1" == "stop" ]; then
  $SUDO launchctl unload /Library/LaunchDaemons/com.cisco.anyconnect.vpnagentd.plist
  $SUDO killall -9 ciscod
  $SUDO killall -9 acwebsecagent
else
   echo Processes:
   ps -ef |egrep /opt/cisco |grep -v grep
   echo CLOSE_WAIT: `netstat -an |grep -c CLOSE_WAIT`
fi
