#!/usr/bin/env bash

###
### my-script -- does something
###
### Usage:
###    my-script <input> <output>
###
### Options:
###    <input>   Input file to read.
###    <output>  Output file to write. Use '-' for stdout.
###    -h        Show this message.
###

help() {
#  sed -En 's/^### ?//;T;p' "$0"
  /usr/local/Cellar/gnu-sed/4.8/gnu-sed -rn 's/^### ?//;T;p' "$0"
}

if [[ $# == 0 ]] || [[ $1 == "-h" ]]; then
  help
  exit 1
fi

