#!/usr/bin/env bash
set -e
set -o pipefail

ERRORS=()

# find all executables and run `shellcheck`
# for f in $(find . -maxdepth 1 -iname "*.sh" | sort -u); do
for f in $(find . -maxdepth 1 | sort -u); do
  if file "$f" | grep --quiet shell; then
    {
      shellcheck "$f" && echo "[OK] Successfully linted $f"
    } || {
      # add to ERRORS
      ERRORS+=("$f")
    }
  fi
done

if [ ${#ERRORS[@]} -eq 0 ]; then
  echo "No errors, hooray"
else
  echo "These files failed shellcheck: ${ERRORS[*]}"
  exit 1
fi
